class LogoSuggestion {
  final String name;
  final String site;

  const LogoSuggestion({
    required this.name,
    required this.site,
  });
}

const logos = [
  LogoSuggestion(name: 'Facebook', site: 'facebook.com'),
  LogoSuggestion(name: 'Instagram', site: 'instagram.com'),
  LogoSuggestion(name: 'X (Twitter)', site: 'x.com'),
  LogoSuggestion(name: 'LinkedIn', site: 'linkedin.com'),
  LogoSuggestion(name: 'Snapchat', site: 'snapchat.com'),
  LogoSuggestion(name: 'TikTok', site: 'tiktok.com'),
  LogoSuggestion(name: 'Reddit', site: 'reddit.com'),
  LogoSuggestion(name: 'Pinterest', site: 'pinterest.com'),
  LogoSuggestion(name: 'Discord', site: 'discord.com'),
  LogoSuggestion(name: 'Threads', site: 'threads.net'),
  LogoSuggestion(name: 'Google', site: 'google.com'),
  LogoSuggestion(name: 'Gmail', site: 'mail.google.com'),
  LogoSuggestion(name: 'Outlook', site: 'outlook.live.com'),
  LogoSuggestion(name: 'Yahoo Mail', site: 'mail.yahoo.com'),
  LogoSuggestion(name: 'Proton Mail', site: 'proton.me'),
  LogoSuggestion(name: 'Zoho Mail', site: 'zoho.com'),
  LogoSuggestion(name: 'WhatsApp', site: 'whatsapp.com'),
  LogoSuggestion(name: 'Telegram', site: 'telegram.org'),
  LogoSuggestion(name: 'Signal', site: 'signal.org'),
  LogoSuggestion(name: 'Skype', site: 'skype.com'),
  LogoSuggestion(name: 'Amazon', site: 'amazon.com'),
  LogoSuggestion(name: 'Flipkart', site: 'flipkart.com'),
  LogoSuggestion(name: 'eBay', site: 'ebay.com'),
  LogoSuggestion(name: 'Etsy', site: 'etsy.com'),
  LogoSuggestion(name: 'AliExpress', site: 'aliexpress.com'),
  LogoSuggestion(name: 'Walmart', site: 'walmart.com'),
  LogoSuggestion(name: 'Target', site: 'target.com'),
  LogoSuggestion(name: 'Best Buy', site: 'bestbuy.com'),
  LogoSuggestion(name: 'Shopify', site: 'shopify.com'),
  LogoSuggestion(name: 'PayPal', site: 'paypal.com'),
  LogoSuggestion(name: 'Stripe', site: 'stripe.com'),
  LogoSuggestion(name: 'Google Pay', site: 'pay.google.com'),
  LogoSuggestion(name: 'Apple ID', site: 'appleid.apple.com'),
  LogoSuggestion(name: 'Venmo', site: 'venmo.com'),
  LogoSuggestion(name: 'Cash App', site: 'cash.app'),
  LogoSuggestion(name: 'Wise', site: 'wise.com'),
  LogoSuggestion(name: 'Revolut', site: 'revolut.com'),
  LogoSuggestion(name: 'Coinbase', site: 'coinbase.com'),
  LogoSuggestion(name: 'Binance', site: 'binance.com'),
  LogoSuggestion(name: 'Netflix', site: 'netflix.com'),
  LogoSuggestion(name: 'Amazon Prime Video', site: 'primevideo.com'),
  LogoSuggestion(name: 'Disney+', site: 'disneyplus.com'),
  LogoSuggestion(name: 'Spotify', site: 'spotify.com'),
  LogoSuggestion(name: 'Apple Music', site: 'music.apple.com'),
  LogoSuggestion(name: 'YouTube', site: 'youtube.com'),
  LogoSuggestion(name: 'Twitch', site: 'twitch.tv'),
  LogoSuggestion(name: 'Hulu', site: 'hulu.com'),
  LogoSuggestion(name: 'Hotstar', site: 'hotstar.com'),
  LogoSuggestion(name: 'SoundCloud', site: 'soundcloud.com'),
  LogoSuggestion(name: 'Microsoft', site: 'microsoft.com'),
  LogoSuggestion(name: 'GitHub', site: 'github.com'),
  LogoSuggestion(name: 'GitLab', site: 'gitlab.com'),
  LogoSuggestion(name: 'Bitbucket', site: 'bitbucket.org'),
  LogoSuggestion(name: 'Slack', site: 'slack.com'),
  LogoSuggestion(name: 'Notion', site: 'notion.so'),
  LogoSuggestion(name: 'Trello', site: 'trello.com'),
  LogoSuggestion(name: 'Asana', site: 'asana.com'),
  LogoSuggestion(name: 'Jira', site: 'atlassian.net'),
  LogoSuggestion(name: 'Zoom', site: 'zoom.us'),
  LogoSuggestion(name: 'Google Drive', site: 'drive.google.com'),
  LogoSuggestion(name: 'Dropbox', site: 'dropbox.com'),
  LogoSuggestion(name: 'OneDrive', site: 'onedrive.live.com'),
  LogoSuggestion(name: 'iCloud', site: 'icloud.com'),
  LogoSuggestion(name: 'Box', site: 'box.com'),
  LogoSuggestion(name: 'Medium', site: 'medium.com'),
  LogoSuggestion(name: 'Quora', site: 'quora.com'),
  LogoSuggestion(name: 'Stack Overflow', site: 'stackoverflow.com'),
  LogoSuggestion(name: 'Coursera', site: 'coursera.org'),
  LogoSuggestion(name: 'Udemy', site: 'udemy.com'),
  LogoSuggestion(name: 'Steam', site: 'steampowered.com'),
  LogoSuggestion(name: 'Epic Games', site: 'epicgames.com'),
  LogoSuggestion(name: 'Xbox', site: 'xbox.com'),
  LogoSuggestion(name: 'PlayStation', site: 'playstation.com'),
  LogoSuggestion(name: 'Nintendo', site: 'nintendo.com'),
  LogoSuggestion(name: 'Roblox', site: 'roblox.com'),
  LogoSuggestion(name: 'Battle.net', site: 'blizzard.com'),
  LogoSuggestion(name: 'EA Origin', site: 'origin.com'),
  LogoSuggestion(name: 'GOG', site: 'gog.com'),
  LogoSuggestion(name: 'Itch.io', site: 'itch.io'),
  LogoSuggestion(name: 'Uber', site: 'uber.com'),
  LogoSuggestion(name: 'Lyft', site: 'lyft.com'),
  LogoSuggestion(name: 'Airbnb', site: 'airbnb.com'),
  LogoSuggestion(name: 'Booking.com', site: 'booking.com'),
  LogoSuggestion(name: 'Expedia', site: 'expedia.com'),
  LogoSuggestion(name: 'TripAdvisor', site: 'tripadvisor.com'),
  LogoSuggestion(name: 'Skyscanner', site: 'skyscanner.com'),
  LogoSuggestion(name: 'Kayak', site: 'kayak.com'),
  LogoSuggestion(name: 'Delta Airlines', site: 'delta.com'),
  LogoSuggestion(name: 'Southwest Airlines', site: 'southwest.com'),
  LogoSuggestion(name: 'MyFitnessPal', site: 'myfitnesspal.com'),
  LogoSuggestion(name: 'Fitbit', site: 'fitbit.com'),
  LogoSuggestion(name: 'Strava', site: 'strava.com'),
  LogoSuggestion(name: 'Peloton', site: 'onepeloton.com'),
  LogoSuggestion(name: 'Nike', site: 'nike.com'),
  LogoSuggestion(name: 'Adidas', site: 'adidas.com'),
  LogoSuggestion(name: 'Under Armour', site: 'underarmour.com'),
  LogoSuggestion(name: 'WW (Weight Watchers)', site: 'weightwatchers.com'),
  LogoSuggestion(name: 'Headspace', site: 'headspace.com'),
  LogoSuggestion(name: 'Calm', site: 'calm.com'),
  LogoSuggestion(name: 'IRCTC', site: 'irctc.co.in'),
  LogoSuggestion(name: 'Aadhaar', site: 'uidai.gov.in'),
  LogoSuggestion(name: 'DigiLocker', site: 'digilocker.gov.in'),
  LogoSuggestion(name: 'Paytm', site: 'paytm.com'),
  LogoSuggestion(name: 'PhonePe', site: 'phonepe.com'),
  LogoSuggestion(name: 'BHIM UPI', site: 'bhimupi.org.in'),
  LogoSuggestion(name: 'Jio', site: 'jio.com'),
  LogoSuggestion(name: 'Airtel', site: 'airtel.in'),
  LogoSuggestion(name: 'Zomato', site: 'zomato.com'),
  LogoSuggestion(name: 'Swiggy', site: 'swiggy.com'),
  LogoSuggestion(name: 'Ola', site: 'olacabs.com'),
  LogoSuggestion(name: 'MakeMyTrip', site: 'makemytrip.com'),
  LogoSuggestion(name: 'Hotstar', site: 'hotstar.com'),
  LogoSuggestion(name: 'Byju’s', site: 'byjus.com'),
  LogoSuggestion(name: 'Alibaba', site: 'alibaba.com'),
  LogoSuggestion(name: 'Spotify', site: 'spotify.com'),
  LogoSuggestion(name: 'Booking.com', site: 'booking.com'),
  LogoSuggestion(name: 'Sony', site: 'sony.com'),
  LogoSuggestion(name: 'Coupang', site: 'coupang.com'),
  LogoSuggestion(name: 'Grab', site: 'grab.com'),
  LogoSuggestion(name: 'Firebase', site: 'firebase.google.com'),
  LogoSuggestion(name: 'Supabase', site: 'supabase.com'),
  LogoSuggestion(name: 'Vercel', site: 'vercel.com'),
  LogoSuggestion(name: 'Netlify', site: 'netlify.com'),
  LogoSuggestion(name: 'AWS', site: 'aws.amazon.com'),
  LogoSuggestion(name: 'Google Cloud', site: 'cloud.google.com'),
  LogoSuggestion(name: 'Azure', site: 'azure.microsoft.com'),
  LogoSuggestion(name: 'DigitalOcean', site: 'digitalocean.com'),
  LogoSuggestion(name: 'State Bank of India (SBI)', site: 'sbi.co.in'),
  LogoSuggestion(name: 'Punjab National Bank', site: 'pnbindia.in'),
  LogoSuggestion(name: 'Bank of Baroda', site: 'bankofbaroda.in'),
  LogoSuggestion(name: 'Canara Bank', site: 'canarabank.com'),
  LogoSuggestion(name: 'Union Bank of India', site: 'unionbankofindia.co.in'),
  LogoSuggestion(name: 'Indian Bank', site: 'indianbank.in'),
  LogoSuggestion(name: 'Bank of India', site: 'bankofindia.co.in'),
  LogoSuggestion(
      name: 'Central Bank of India', site: 'centralbankofindia.co.in'),
  LogoSuggestion(name: 'Indian Overseas Bank', site: 'iob.in'),
  LogoSuggestion(name: 'UCO Bank', site: 'ucobank.com'),
  LogoSuggestion(name: 'Bank of Maharashtra', site: 'bankofmaharashtra.in'),
  LogoSuggestion(name: 'Punjab & Sind Bank', site: 'punjabandsindbank.co.in'),
  LogoSuggestion(name: 'HDFC Bank', site: 'hdfcbank.com'),
  LogoSuggestion(name: 'ICICI Bank', site: 'icicibank.com'),
  LogoSuggestion(name: 'Axis Bank', site: 'axisbank.com'),
  LogoSuggestion(name: 'Kotak Mahindra Bank', site: 'kotak.com'),
  LogoSuggestion(name: 'IndusInd Bank', site: 'indusind.com'),
  LogoSuggestion(name: 'Yes Bank', site: 'yesbank.in'),
  LogoSuggestion(name: 'IDFC First Bank', site: 'idfcfirstbank.com'),
  LogoSuggestion(name: 'Federal Bank', site: 'federalbank.co.in'),
  LogoSuggestion(name: 'South Indian Bank', site: 'southindianbank.com'),
  LogoSuggestion(name: 'RBL Bank', site: 'rblbank.com'),
  LogoSuggestion(name: 'Bandhan Bank', site: 'bandhanbank.com'),
  LogoSuggestion(name: 'City Union Bank', site: 'cityunionbank.com'),
  LogoSuggestion(name: 'Karur Vysya Bank', site: 'kvb.co.in'),
  LogoSuggestion(name: 'DCB Bank', site: 'dcbbank.com'),
  LogoSuggestion(name: 'AU Small Finance Bank', site: 'aubank.in'),
  LogoSuggestion(name: 'Ujjivan Small Finance Bank', site: 'ujjivansfb.in'),
  LogoSuggestion(name: 'Equitas Small Finance Bank', site: 'equitasbank.com'),
  LogoSuggestion(name: 'Jana Small Finance Bank', site: 'janabank.com'),
  LogoSuggestion(name: 'Suryoday Small Finance Bank', site: 'suryodaybank.com'),
  LogoSuggestion(name: 'ESAF Small Finance Bank', site: 'esafbank.com'),
  LogoSuggestion(name: 'Amazon Pay', site: 'amazonpay.in'),
  LogoSuggestion(name: 'CRED', site: 'cred.club'),
  LogoSuggestion(name: 'Mobikwik', site: 'mobikwik.com'),
  LogoSuggestion(name: 'Freecharge', site: 'freecharge.in'),
  LogoSuggestion(name: 'Airtel Payments Bank', site: 'airtel.in/bank'),
  LogoSuggestion(name: 'PayZapp (HDFC)', site: 'payzapp.com'),
  LogoSuggestion(name: 'Zerodha', site: 'zerodha.com'),
  LogoSuggestion(name: 'Groww', site: 'groww.in'),
  LogoSuggestion(name: 'Upstox', site: 'upstox.com'),
  LogoSuggestion(name: 'Angel One', site: 'angelone.in'),
  LogoSuggestion(name: 'ICICI Direct', site: 'icicidirect.com'),
  LogoSuggestion(name: 'HDFC Securities', site: 'hdfcsec.com'),
  LogoSuggestion(name: 'Paytm Money', site: 'paytmmoney.com'),
  LogoSuggestion(name: 'Coin by Zerodha', site: 'coin.zerodha.com'),
  LogoSuggestion(name: 'ET Money', site: 'etmoney.com'),
  LogoSuggestion(name: 'Kuvera', site: 'kuvera.in'),
  LogoSuggestion(name: 'Amazon India', site: 'amazon.in'),
  LogoSuggestion(name: 'Myntra', site: 'myntra.com'),
  LogoSuggestion(name: 'Ajio', site: 'ajio.com'),
  LogoSuggestion(name: 'Meesho', site: 'meesho.com'),
  LogoSuggestion(name: 'Snapdeal', site: 'snapdeal.com'),
  LogoSuggestion(name: 'Tata CLiQ', site: 'tatacliq.com'),
  LogoSuggestion(name: 'Cleartrip', site: 'cleartrip.com'),
  LogoSuggestion(name: 'Yatra', site: 'yatra.com'),
  LogoSuggestion(name: 'Blinkit', site: 'blinkit.com'),
  LogoSuggestion(name: 'BigBasket', site: 'bigbasket.com'),
  LogoSuggestion(name: 'Income Tax Portal', site: 'incometax.gov.in'),
  LogoSuggestion(name: 'EPFO', site: 'epfindia.gov.in'),
  LogoSuggestion(name: 'MyGov India', site: 'mygov.in'),
  LogoSuggestion(name: 'GST Portal', site: 'gst.gov.in'),
];
